name: 'dbtdeepPromo'
version: '1.0.0'

profile: 'dbtdeepPromo'
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/
# directory as views. These settings can be overridden in the individual model
# files using the `{{ config(...) }}` macro.
models:
  dbtdeepPromo:
    staging:
       +pre-hook: 
         - "{{ apply_dev_limit() }}"
         - "{% if should_reset_data() %} DELETE FROM {{ this }}; {% endif %}"
       +post-hook: 
         - "CREATE INDEX IF NOT EXISTS {{ this.name }}_idx ON {{ this }} (id_items, last_updated_date)"
         - "ANALYZE {{ this }}"
       +materialized: incremental
       +schema: "{{ target.name }}_staging"
    intermediate:
      +pre-hook: 
         - "{{ apply_dev_limit() }}"
         - "{% if should_reset_data() %} DELETE FROM {{ this }}; {% endif %}"
      +materialized: table
      +schema: "{{ target.name }}_intermediate"
    marts:
      +pre-hook: 
         - "{{ apply_dev_limit() }}"
         - "{% if should_reset_data() %} DELETE FROM {{ this }}; {% endif %}"
      +materialized: incremental
      +schema: "{{ target.name }}_marts"

vars:
  row_limit_dev: 100000
  reset_data: false
  ana_scenario: 'ACTUAL_OFFICIAL'
  ana_year: 2025
  ref_scenario: 'FLASH_OFFICIAL'
  ref_year: 2024
  period: 'month'         # possible: annual, semester, quarter, month
  granularity: 'country, region, department, city, store_id'
 
  # customer_types: "'Fidélité', 'Entreprise', 'Particulier'"
  # customer_segments: "'VIP', 'PREMIUM', 'CORPORATE'"
  

  # product_categories: "'TV', 'Audio', 'Savons'"