dbtdeepPromo:
  target: dev
  outputs:
    dev:
      type: sqlserver
      driver: "ODBC Driver 17 for SQL Server"
      server: localhost
      port: 1433
      database: master
      schema: dbo
      user: SA
      password: Chniadma04@
      encrypt: false
      trust_cert: False